apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pacman
          env:
            - name: ENVIRONMENT
              value: development