apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app2
        env:
        - name: ENV
          value: "production"
